### ISSUE TITLE
Improved website user experience

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2796]
Make it easier for consumers of PatternFly to find the content and documentation they need using the PatternFly website. Areas to address include:

* Information architecture - making it easier to find what I'm looking for.
* Component pages - improve overall usefulness and readability.
* Home page - make the home page more useful and current.
* Navigation - make it easier to browse content on the site.

| Issue | Milestone | Assignee |
| --- | --- | --- |
| [Implement tertiary nav in the sidebar](https://github.com/patternfly/patternfly-org/issues/2906) | 2022.12 |  |
| [Component page - add short description to header](https://github.com/patternfly/patternfly-org/issues/2989) | 2022.12 | @evwilkin |
| [Component page - add descriptions for component examples](https://github.com/patternfly/patternfly-org/issues/2990) | 2022.12 | @edonehoo |
| [Add the ability to have "knobs" to set props on React example that live outside of the example itself.](https://github.com/patternfly/patternfly-org/issues/2991) | | |
| [Add new Patterns section to the website](https://github.com/patternfly/patternfly-org/issues/3094) | 2022.12 |  |
| [Revise website IA fpr improved findability](https://github.com/patternfly/patternfly-org/issues/3095) | 2022.13  |  |
| [Create template for demo page](https://github.com/patternfly/patternfly-org/issues/2935) | 2022.13 | @kmcfaul @wolfeallison |
| [Build a component catalog page](https://github.com/patternfly/patternfly-org/issues/2989) | 2022.13 | @evwilkin  |

- [x] [IA study - research follow-up](https://github.com/patternfly/patternfly-org/issues/2789)
- [x] [Improvements to Component pages](https://github.com/patternfly/patternfly-org/issues/2843)
- [x] [Website: Make it easier to differentiate component from the background on component pages](https://github.com/patternfly/patternfly-design/issues/1015)
- [x] [Add blog highlights to website home page](https://github.com/patternfly/patternfly-design/issues/1069)
- [x] [Right-hand in-page table of contents on docs pages is hidden below 1450px](https://github.com/patternfly/patternfly-design/issues/1096)
- [x] [Consider how we could retire component demos on PF.org](https://github.com/patternfly/patternfly-design/issues/1098)
- [x] [A more visual/catalog-like representation of all our components](https://github.com/patternfly/patternfly-design/issues/1099)
- [x] [Define header styling for React examples on website](https://github.com/patternfly/patternfly-design/issues/1139)
- [x] [Recommend website IA changes based on UX research results](https://github.com/patternfly/patternfly-design/issues/1141)
- [x] [Reconsider design of component pages on PF website](https://github.com/patternfly/patternfly-design/issues/1146)
- [x] [TreeJack study to validate proposed website IA changes](https://github.com/patternfly/patternfly-design/issues/1153)

**Comment by mcarrano** [comment]
@evwilkin I created this epic to collect some of the various issues/tasks we have in progress around improving the website UX. Feel free to add anything I might have missed.

**Comment by evwilkin** [comment]
| Issue | Milestone | Assignee |
| --- | --- | --- |
| [Implement tertiary nav in the sidebar](https://github.com/patternfly/patternfly-org/issues/2906) | 2022.11 |  |
| [Component page - add short description to header](https://github.com/patternfly/patternfly-org/issues/2989) | 2022.11 | @evwilkin |
| [Component page - add descriptions for component examples](https://github.com/patternfly/patternfly-org/issues/2990) | 2022.10 | @edonehoo |
| [Add the ability to have "knobs" to set props on React example that live outside of the example itself.](https://github.com/patternfly/patternfly-org/issues/2991) | | |
| [Add new Patterns section to the website](https://github.com/patternfly/patternfly-org/issues/3094) | 2022.12 |  |
| [Revise website IA fpr improved findability](https://github.com/patternfly/patternfly-org/issues/3095) | 2022.12  |  |
| [Create template for demo page](https://github.com/patternfly/patternfly-org/issues/2935) | 2022.13 | @kmcfaul @wolfeallison |

- [x] [IA study - research follow-up](https://github.com/patternfly/patternfly-org/issues/2789)
- [x] [Improvements to Component pages](https://github.com/patternfly/patternfly-org/issues/2843)
- [x] [Website: Make it easier to differentiate component from the background on component pages](https://github.com/patternfly/patternfly-design/issues/1015)
- [x] [Add blog highlights to website home page](https://github.com/patternfly/patternfly-design/issues/1069)
- [x] [Right-hand in-page table of contents on docs pages is hidden below 1450px](https://github.com/patternfly/patternfly-design/issues/1096)
- [x] [Consider how we could retire component demos on PF.org](https://github.com/patternfly/patternfly-design/issues/1098)
- [x] [A more visual/catalog-like representation of all our components](https://github.com/patternfly/patternfly-design/issues/1099)
- [x] [Define header styling for React examples on website](https://github.com/patternfly/patternfly-design/issues/1139)
- [x] [Recommend website IA changes based on UX research results](https://github.com/patternfly/patternfly-design/issues/1141)
- [x] [Reconsider design of component pages on PF website](https://github.com/patternfly/patternfly-design/issues/1146)
- [x] [TreeJack study to validate proposed website IA changes](https://github.com/patternfly/patternfly-design/issues/1153)

**Comment by mcarrano** [comment]
Closing this in favor of using linked issues to track progress.
