### ISSUE TITLE
Enable extension docs on PF website

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2903]
This Epic will track the work towards enabling extensions to include their docs & examples on the PatternFly.org website.

- [Discussion notes doc](https://docs.google.com/document/d/1m5H3CyQgCEXch9nUpmOzO8fnNciFMSr6Qz3OXJ1YaUw/edit)

PatternFly extensions should be able to include their documentation on patternfly.org even if those examples & documentation live in an external repo.  We should update the build process and provide a template for external extensions to adhere to in order to correctly pull their docs into the website, apply additional testing/linting as needed to ensure these external sources will not break the build or negatively affect the website, and add quick starts, catalog view, and topology docs to the website.

- [x] https://github.com/patternfly/patternfly-org/issues/2905
- [x] https://github.com/patternfly/patternfly-org/issues/2907
- [x] https://github.com/patternfly/patternfly-org/issues/2883
- [x] #3185 
- [x] https://github.com/patternfly/patternfly-org/issues/2910
- [x] https://github.com/patternfly/patternfly-org/issues/2909
- [x] https://github.com/patternfly/patternfly-org/issues/2906
- [ ] https://github.com/patternfly/patternfly-org/issues/2908

**Comment by evwilkin** [comment]
- [ ] Update build process to [pull in docus/examples](https://github.com/patternfly/patternfly-org/blob/main/packages/v4/patternfly-docs.source.js) from external sources
- [ ] Implement [tertiary nav seen here](https://github.com/patternfly/patternfly-org/issues/2883#issuecomment-1089225664) to list different components within each extension (sidenav items [created here](https://github.com/patternfly/patternfly-org/blob/main/packages/v4/patternfly-docs.config.js#L14) and [implemented here](https://github.com/patternfly/patternfly-org/blob/main/packages/v4/patternfly-docs.source.js#L12)
- [ ] Create template that external sources should follow to ensure their examples/docs are pulled in & integrated into the Extensions section of the PF website correctly
- [ ] Add [quick starts](https://github.com/patternfly/patternfly-quickstarts) documentation to site
- [ ] Add [topology](https://github.com/patternfly/patternfly-react/tree/main/packages/react-topology) documentation to site
- [ ] Add [catalog view](https://github.com/patternfly/patternfly-react/tree/main/packages/react-catalog-view-extension) documentation to site
