### ISSUE TITLE
Extract Catalog View repo and begin displaying documentation directly on the PatternFly site

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#3332]
- [x] [extract the Catalog View package from the PF React repo](https://github.com/patternfly/patternfly-react/issues/8473)
- [x] [restructure Catalog View docs with patternflly-docs](https://github.com/patternfly/react-catalog-view)
- [x] [update org accordingly to begin displaying Catalog View docs directly on the site](https://github.com/patternfly/patternfly-org/issues/3333)

**Comment by wise-king-sullyman** [comment]
Closing as all the items in this issue have been addressed.
