### ISSUE TITLE
Indentify and resolve broken links after IA reorganization

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3437]
We are currently in the process of moving around pages on the website per https://github.com/patternfly/patternfly-org/issues/3095. This will inevitably break internal links within the website. Need a way of testing for and identifying these issues and fixing them.

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-org/pull/3550
- [ ] https://github.com/patternfly/patternfly-org/pull/3556
- [ ] https://github.com/patternfly/patternfly-org/pull/3557
- [ ] https://github.com/patternfly/patternfly-org/pull/3560
- [ ] https://github.com/patternfly/patternfly-org/pull/3564
- [ ] https://github.com/patternfly/patternfly-org/pull/3566
- [ ] https://github.com/patternfly/patternfly-org/pull/3563
```

**Comment by evwilkin** [comment]
One manual but free online tool I've just tried is https://www.brokenlinkcheck.com/ - it's found 109 broken links currently on the site, along with which page they live on and what the URL text is.  Might not be great for an automated solution, but seems decent for 1-off checks

**Comment by mcarrano** [comment]
I ran the link checker again against the current V5 staging site (https://dpu07u5c4ng26.cloudfront.net/v4/). It returned 80 broken links. A copy of the report can be in the attachment.

[Archive.zip](https://github.com/patternfly/patternfly-org/files/11492050/Archive.zip)

**Comment by mcarrano** [comment]
Here is the information above converted to a Google doc: https://docs.google.com/document/d/1dhuOvfjQA5PWRkBuxxqXSjQPEqHWxgHE/edit?usp=sharing&ouid=103273273844469477521&rtpof=true&sd=true

**Comment by evwilkin** [comment]
@kmcfaul may have feedback as she's working on a related issue of setting up redirects.
