### ISSUE TITLE
Add documentation to website for products interested in adopting/implementing dark theme

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3514]
Including:
```[tasklist]
### Tasks
- [ ] Display values of variables when in dark theme
- [ ] How-to for the theme switch
- [ ] what else?
- [ ] [use handbook as starting point](https://docs.google.com/document/d/1mRYEfUoOjTsSt7hiqjbeplqhfo3_rVDO0QqMj2p67pw/edit?usp=sharing)
```
