### ISSUE TITLE
Enhancements & bug fixes for sectionGallery

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#3568]
Add enhancements as initially tested in #3558 to allow more flexibility when using `sectionGallery` component within different navigation sections.

```[tasklist]
### Tasks
- [x] Only render `DataListCell` in list view if item has an illustration (rather than an empty cell that conditionally renders the image)
- [x] Add `initialLayout` prop allowing user to set the initial layout (grid or list)
- [x] Exclude gallery page from gallery results by checking location.pathname does not end with slug (rather than does not equal slug) - accounts for /v4 or similar prefix values
- [x] Handle case where no illustrations are provided
- [x] Handle subsections don't have title or id, need to provide fallback value
- [x] Toggle summary text within cards in grid view
```
