### ISSUE TITLE
Review and update Get started pages

### ISSUE THREAD

**Issue by edonehoo** [patternfly/patternfly-org#3649]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-org/issues/3897
- [ ] https://github.com/patternfly/patternfly-org/issues/3914
- [ ] https://github.com/patternfly/patternfly-org/issues/3889
- [ ] https://github.com/patternfly/patternfly-org/issues/3888
- [ ] https://github.com/patternfly/patternfly-org/issues/3921
```
