### ISSUE TITLE
Review and update Accessibility guidelines

### ISSUE THREAD

**Issue by edonehoo** [patternfly/patternfly-org#3695]
Makes progress on #3544

Note: be sure to edit Trapping focus section of Product development guide 
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-org/issues/3741
- [ ] https://github.com/patternfly/patternfly-org/issues/3773
- [ ] https://github.com/patternfly/patternfly-org/issues/3771
- [ ] https://github.com/patternfly/patternfly-org/issues/3777
- [ ] https://github.com/patternfly/patternfly-org/issues/3775
- [ ] https://github.com/patternfly/patternfly-org/issues/3778
```

**Comment by edonehoo** [comment]
🎉
