### ISSUE TITLE
Update & test website to support Penta theming

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#3764]
As theming is added in [Core](https://github.com/patternfly/pf-roadmap/issues/58) & [React](https://github.com/patternfly/patternfly-react/issues/9413) we should evaluate steps needed to support them accurately on the website.

Possible steps include:

```[tasklist]
### Tasks
- [ ] Pull prereleases into website & test
- [ ] Identify & resolve any custom styles
- [ ] Determine interaction and implementation for switching between themes.  Is this site-wide, per-example...?
- [ ] Flag static assets which need to be updated.
```

**Comment by jessiehuff** [comment]
Closing this issue and reopened one for the bit of work remaining: https://github.com/patternfly/patternfly-org/issues/4076
