### ISSUE TITLE
Set up v6 branch and development workflows

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3835]
- [x] branch v6
- [x] pull in v6 alphas of core/react
- [x] publish a v6 alpha of docs-framework
- [x] publish a v6 staging site of org
- [x] update logo in masthead to use inline svg
- [x] pull in design tokens docs

**Comment by nicolethoen** [comment]
done!
