### ISSUE TITLE
V6 support in Org

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#3854]
This epic will track any & all Org updates required to support V6 development, documentation, release workflows, etc.

```[tasklist]
### Infrastructure & workflow tasks
- [ ] https://github.com/patternfly/patternfly-org/issues/3835
- [ ] https://github.com/patternfly/patternfly-org/pull/3845
```

```[tasklist]
### Website styling/theming
- [ ] https://github.com/patternfly/patternfly-org/issues/3764
- [ ] https://github.com/patternfly/patternfly-org/issues/3756
- [ ] https://github.com/patternfly/patternfly-org/issues/3859
- [ ] https://github.com/patternfly/patternfly-org/issues/3877
- [ ] https://github.com/patternfly/patternfly-org/issues/3909
- [ ] https://github.com/patternfly/patternfly-org/issues/3910
```

**Comment by andrew-ronaldson** [comment]
For the short-term the Extensions section will be hidden from the Alpha staging site while we go through the list and make all the necessary uppates.. There are Epics tracking these from Design > Dev work

**Comment by andrew-ronaldson** [comment]
PR up for https://github.com/patternfly/patternfly-org/issues/3910
