### ISSUE TITLE
Docs - Replace static variables with Design tokens across org.

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-org#3994]
This Epic tracks the docs updates needed for the v6 org site.

```[tasklist]
### Pages to update
- [ ] https://github.com/patternfly/patternfly-org/issues/4040
- [ ] https://github.com/patternfly/patternfly-org/issues/4041
- [ ] https://github.com/patternfly/patternfly-org/issues/4042
- [ ] https://github.com/patternfly/patternfly-org/issues/4130
```
