### ISSUE TITLE
Prep v6 beta release

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#4113]
```[tasklist]
### Tasks
- [ ] Make sure all extensions are up to date with all changes on main branch
- [ ] Identify beta release candidate
- [ ] Rename branches (v6 -> main, main -> v5)
- [ ] Update configs in all repos to stop releasing alphas and begin releasing prereleases
- [ ] Update configs in v5 branches to continue releasing v5
- [ ] Update testing template and let testers/products know beta candidates
- [ ] Coordinate with Erin about communications around beta release
- [ ] Update all extensions to use beta release
- [ ] Let all products/testers know the beta versions (update testing template)
```
