### ISSUE TITLE
PF6 Design guideline updates

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-org#4235]
```[tasklist]
### Component guideline updates
- [ ] Guideline updates: About modal
- [ ]  Guideline updates: Accordions
- [ ]  Guideline updates: Action list
- [ ]  Guideline updates: Alert
- [ ]  Guideline updates: Avatar
- [ ]  Guideline updates: Banner
- [ ]  Guideline updates: Breadcrumb
- [ ]  Guideline updates: Buttons
- [ ]  Guideline updates: Cards & Tiles
- [ ]  Guideline updates: Copy clipboard
- [ ]  Guideline updates: Code block
- [ ]  Guideline updates: Code editor
- [ ]  Guideline updates: Data list
- [ ]  Guideline updates: Calendar month
- [ ]  Guideline updates: Decription list
- [ ]  Guideline updates: Divider
- [ ]  Guideline updates: Drag and drop
- [ ]  Guideline updates: Drawer
- [ ]  Guideline updates: Dual list selector
- [ ]  Guideline updates: Empty state
- [ ]  Guideline updates: Expandable section
- [ ]  Guideline updates: File uploads
- [ ]  Guideline updates: Forms
- [ ]  Guideline updates: Hint
- [ ]  Guideline updates: Inline edit
- [ ]  Guideline updates: Input group
- [ ]  Guideline updates: Jump links
- [ ] Guideline updates: Label
- [ ] Guideline updates: List & Simple list
- [ ] Guideline updates: Login page
- [ ] Guideline updates: Masthead
- [ ] Guideline updates: Dropdown
- [ ] Guideline updates: Menu
- [ ] Guideline updates: Menu tggle
- [ ] Guideline updates: Select
- [ ] Guideline updates: Modal
- [ ] Guideline updates: Navigation
- [ ] Guideline updates: Notification badge (stateful button)
- [ ] Guideline updates: Notification drawer
- [ ] Guideline updates: Number inputs
- [ ] Guideline updates: Overflow menu
- [ ] Guideline updates: Page
- [ ] Guideline updates: Pagination
- [ ] Guideline updates: Panel
- [ ] Guideline updates: Password strength
- [ ] Guideline updates: Popover & Tooltips
- [ ] Guideline updates: Progress & Progress stepper
- [ ] Guideline updates: Search input
- [ ] Guideline updates: Sidebar
- [ ] Guideline updates: Slider
- [ ] Guideline updates: Table
- [ ] Guideline updates: Tabs
- [ ] Guideline updates: Text input groups
- [ ] Guideline updates: Timestamp
- [ ] Guideline updates: Toggle group
- [ ] Guideline updates: Toolbar
- [ ] Guideline updates: Treeview
- [ ] Guideline updates: Truncate
- [ ] Guideline updates: Wizard
```

**Comment by edonehoo** [comment]
Note: this will also close https://github.com/patternfly/patternfly-org/issues/4076 (or we could close that one in favor of this more detailed epic)
