### ISSUE TITLE
Example component / template has been created

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#4458]
# Descriptions: 
Figure out the Markdowns front mater schema / api so that we can move the markdown files from the current documentation framework over to Astro. We can use a simple documentation page instead of a component.

## Tasks:
- [ ] Example of a documentation markdown page running in astro framework
- [ ] Renders to the correct route in the page and navigation.  This would be the correct site to tell the navigation where to render.
- [ ] Any Zod schema added and built out to support MD has been added
- [ ] Code is tested and in CI/CD.

### Resources:
* [Landing Page](https://www.patternfly.org/)
* [MDX](https://mdxjs.com/)
* [Zod documentation schema](https://zod.dev/) 
* [JSX support and React support](https://docs.astro.build/en/guides/integrations-guide/react/#installation)
